--- #YAML:1.0
name:                Pod-SpeakIt-MacSpeech
version:             0.10_01
abstract:            This is what the module does
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Mac::Carbon:                   0.77
    Mac::Files:                    0
    Mac::Speech:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
